import type { Restaurant } from "./types"

export const restaurants: Restaurant[] = [
  {
    id: 1,
    name: "Burger Palace",
    category: "Hamburguesas",
    image: "/placeholder.svg?height=120&width=200&text=Burger+Palace",
    rating: 4.5,
    deliveryTime: "25-35 min",
    isPromoted: true,
    products: [
      {
        id: 101,
        name: "Hamburguesa Clásica",
        description: "Carne de res, lechuga, tomate, cebolla y salsa especial",
        price: 8.5,
        image: "/placeholder.svg?height=100&width=100&text=Burger",
        category: "Hamburguesas",
        restaurantId: 1,
      },
      {
        id: 102,
        name: "Hamburguesa Doble",
        description: "Doble carne, queso, bacon y papas fritas",
        price: 12.0,
        image: "/placeholder.svg?height=100&width=100&text=Double+Burger",
        category: "Hamburguesas",
        restaurantId: 1,
      },
      {
        id: 103,
        name: "Papas Fritas",
        description: "Papas crujientes con sal marina",
        price: 3.5,
        image: "/placeholder.svg?height=100&width=100&text=Fries",
        category: "Acompañantes",
        restaurantId: 1,
      },
      {
        id: 104,
        name: "Coca Cola",
        description: "Refresco 500ml",
        price: 2.0,
        image: "/placeholder.svg?height=100&width=100&text=Coke",
        category: "Bebidas",
        restaurantId: 1,
      },
    ],
  },
  {
    id: 2,
    name: "Pizza Express",
    category: "Pizzas",
    image: "/placeholder.svg?height=120&width=200&text=Pizza+Express",
    rating: 4.3,
    deliveryTime: "30-40 min",
    isPromoted: false,
    products: [
      {
        id: 201,
        name: "Pizza Margherita",
        description: "Salsa de tomate, mozzarella y albahaca fresca",
        price: 15.0,
        image: "/placeholder.svg?height=100&width=100&text=Margherita",
        category: "Pizzas",
        restaurantId: 2,
      },
      {
        id: 202,
        name: "Pizza Pepperoni",
        description: "Salsa de tomate, mozzarella y pepperoni",
        price: 18.0,
        image: "/placeholder.svg?height=100&width=100&text=Pepperoni",
        category: "Pizzas",
        restaurantId: 2,
      },
    ],
  },
  {
    id: 3,
    name: "Farmacia San Felipe",
    category: "Farmacia",
    image: "/placeholder.svg?height=120&width=200&text=Farmacia",
    rating: 4.7,
    deliveryTime: "15-25 min",
    isPromoted: false,
    products: [
      {
        id: 301,
        name: "Acetaminofén 500mg",
        description: "Caja con 20 tabletas",
        price: 5.0,
        image: "/placeholder.svg?height=100&width=100&text=Medicine",
        category: "Medicamentos",
        restaurantId: 3,
      },
    ],
  },
]
