export const mockRestaurants = [
  {
    id: "1",
    name: "McDonald's Turbo",
    image: "/placeholder.svg?height=200&width=400&text=McDonalds",
    rating: 4.8,
    deliveryTime: "11 min",
    deliveryFee: "$690.00",
    distance: "387 mts",
    category: "Comida Rápida",
    isTurbo: true,
    isPromoted: true,
    discount: "Hasta 60% Off",
    products: [
      {
        id: "p1",
        name: "Big Mac",
        image: "/placeholder.svg?height=150&width=150&text=Big+Mac",
        price: 8.99,
        originalPrice: 12.99,
        discount: 30,
        category: "Hamburguesas",
        restaurantId: "1",
        description:
          "Dos hamburguesas de carne 100% res, salsa especial, lechuga, queso, pepinillos, cebolla en pan con semillas de sésamo.",
        rating: 4.7,
      },
      {
        id: "p2",
        name: "McNuggets x10",
        image: "/placeholder.svg?height=150&width=150&text=McNuggets",
        price: 6.99,
        originalPrice: 8.99,
        discount: 22,
        category: "Pollo",
        restaurantId: "1",
        description: "10 piezas de pollo empanizado con tu salsa favorita.",
        rating: 4.5,
      },
    ],
  },
  {
    id: "2",
    name: "Pizza Hut Express",
    image: "/placeholder.svg?height=200&width=400&text=Pizza+Hut",
    rating: 4.6,
    deliveryTime: "25 min",
    deliveryFee: "$590.00",
    distance: "520 mts",
    category: "Pizzas",
    isTurbo: false,
    isPromoted: false,
    products: [
      {
        id: "p3",
        name: "Pizza Pepperoni Personal",
        image: "/placeholder.svg?height=150&width=150&text=Pizza+Pepperoni",
        price: 12.99,
        originalPrice: 16.99,
        discount: 25,
        category: "Pizzas",
        restaurantId: "2",
        description: "Pizza personal con pepperoni, queso mozzarella y salsa de tomate.",
        rating: 4.8,
      },
    ],
  },
  {
    id: "3",
    name: "Farmacia San Felipe",
    image: "/placeholder.svg?height=200&width=400&text=Farmacia",
    rating: 4.9,
    deliveryTime: "15 min",
    deliveryFee: "$300.00",
    distance: "200 mts",
    category: "Farmacia",
    isTurbo: true,
    isPromoted: true,
    products: [
      {
        id: "p4",
        name: "Acetaminofén 500mg",
        image: "/placeholder.svg?height=150&width=150&text=Acetaminofen",
        price: 3.5,
        category: "Medicamentos",
        restaurantId: "3",
        description: "Caja con 20 tabletas de acetaminofén 500mg para dolor y fiebre.",
        rating: 4.9,
      },
    ],
  },
]

export const mockOffers = [
  {
    id: "o1",
    name: "Combo Burger Deluxe",
    image: "/placeholder.svg?height=150&width=150&text=Combo+Burger",
    price: 9.99,
    originalPrice: 15.99,
    discount: 38,
    category: "Combos",
    restaurantId: "1",
    description: "Hamburguesa doble con papas fritas y bebida grande.",
    rating: 4.6,
  },
  {
    id: "o2",
    name: "Pizza Familiar 50% OFF",
    image: "/placeholder.svg?height=150&width=150&text=Pizza+Familiar",
    price: 19.99,
    originalPrice: 39.99,
    discount: 50,
    category: "Pizzas",
    restaurantId: "2",
    description: "Pizza familiar de 4 ingredientes a tu elección.",
    rating: 4.7,
  },
  {
    id: "o3",
    name: "Kit Vitaminas",
    image: "/placeholder.svg?height=150&width=150&text=Vitaminas",
    price: 12.99,
    originalPrice: 19.99,
    discount: 35,
    category: "Suplementos",
    restaurantId: "3",
    description: "Kit completo de vitaminas esenciales para 30 días.",
    rating: 4.8,
  },
]

/**
 * Flatten every product from `mockRestaurants` and append the stand-alone
 * `mockOffers` so any module can import a single `mockProducts` list.
 */
export const mockProducts = [...mockRestaurants.flatMap((r) => r.products ?? []), ...mockOffers]
